### ISSUE TITLE
[BUG] Photo upload not working

### ISSUE THREAD

**Issue by filippofontana** [AmruthPillai/Reactive-Resume#660] opened 2022-03-12 11:50 UTC
**Describe the bug**
The candidate picture is not loaded in the site.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new resume
2. Upload a photo
3. The photo is not loaded and showed

**Expected behaviour**
The photo should be loaded and showed in the resume

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox

**Additional context**
The browser console says the following:
`Uncaught (in promise) Object { statusCode: 500, message: "Internal server error" }`

**Comment by AmruthPillai** [comment] 2022-03-12 11:51
Duplicate of https://github.com/AmruthPillai/Reactive-Resume/issues/658, resolved now.
Should be fixed on production in the next version (will be up in few minutes).

**Comment by filippofontana** [comment] 2022-03-12 11:52
Thank you, I did not see #658, sorry for that.

**Closed by AmruthPillai** 2022-03-12 11:51 UTC
Labels: bug, duplicate
