### ISSUE TITLE
Date Function

### ISSUE THREAD

**Issue by peckj22** [AmruthPillai/Reactive-Resume#549] opened 2021-08-09 16:37 UTC
Currently, if you set the date to today, it just shows as "August 2021". A feature where to check where it says "Still working here?" or "Currently employed", etc. and the date shown is "January 2021 - Present". Thanks!

**Comment by stfkolev** [comment] 2021-08-10 13:29
Possible duplicate of #539

**Comment by AmruthPillai** [comment] 2022-03-08 13:33
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!

**Closed by AmruthPillai** 2022-03-08 13:33 UTC
