### ISSUE TITLE
Load demo data from the currently selected language[FEATURE] 

### ISSUE THREAD

**Issue by ghimciucmihai** [AmruthPillai/Reactive-Resume#868] opened 2022-04-30 20:54 UTC
Could we have this function? Have a demo date for all languages?
If the user chooses his Italian language, he will be able to upload the demo date also in Italian!

**Comment by AmruthPillai** [comment] 2022-05-01 05:28
Duplicate of https://github.com/AmruthPillai/Reactive-Resume/issues/793, closing this issue for now.

**Closed by AmruthPillai** 2022-05-01 05:28 UTC
Labels: duplicate, enhancement
