### ISSUE TITLE
Date wrap issues

### ISSUE THREAD

**Issue by Axiso** [AmruthPillai/Reactive-Resume#758] opened 2022-03-22 05:03 UTC
**Expected behavior**
The start and end dates should appear on the same line

**Screenshots**
![image](https://user-images.githubusercontent.com/26027395/159411466-8dad3fea-3427-4d70-87b7-22de05aa447e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser :chrome
 - Version :99.0.4844.74

**Comment by chandiwalaaadhar** [comment] 2022-03-22 05:42
Issue is Duplicate of #753

**Comment by AmruthPillai** [comment] 2022-03-22 06:32
The current way to solve this would be to reduce the number of columns for these sections. Any other suggestions on how to dynamically have both title and date side-by-side or on top of each other?

**Comment by Axiso** [comment] 2022-03-22 07:52
I get it, thanks
![image](https://user-images.githubusercontent.com/26027395/159432993-624cf6ad-9e2f-43e0-9882-7f5190239713.png)

**Closed** 2022-03-22 07:52 UTC
Labels: bug, duplicate
