### ISSUE TITLE
[FEATURE] Different date formats across the app

### ISSUE THREAD

**Issue by KO1122** [AmruthPillai/Reactive-Resume#1006] opened 2022-09-18 15:49 UTC
**Describe the solution you'd like**
It would be great if the user would be able to use different date formats across the app. For example, I would like to use the MMMM DD, YYYY format for my birthdate. However, I'd like to use the MM/YYYY format for my Education dates.

**Comment by Shad0wGh0st12** [comment] 2022-11-15 06:12
Hi RuteshRathod,
If I understand KO1122 correctly this is not exactly what is is looking for.
I think he would like to set the global settings to MMM YYY -and- have a different format for his DoB like MM/DD/YYYY at the same time.
Your screenshot changes the settings for all dates in the app.

At the moment it seems impossible to have that. Or am I missing something?

I am writing here, because I would like the same as him.

**Comment by AmruthPillai** [comment] 2022-11-23 11:25
Duplicate of #802, will continue to track the conversation and development from there. Thank you for raising this issue :)

**Closed by AmruthPillai** 2022-11-23 11:25 UTC
Labels: enhancement
