### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by Amir8212Dv** [AmruthPillai/Reactive-Resume#968] opened 2022-08-10 22:23 UTC
The problem is I can use custom CSS feature to give personal style to each section.
My suggested solution is to set an `id` attribute with the value of the section's name for each section's element

**Comment by AmruthPillai** [comment] 2022-08-22 18:02
Duplicate of https://github.com/AmruthPillai/Reactive-Resume/issues/946#issue-1307867853

**Closed by AmruthPillai** 2022-08-22 18:02 UTC
Labels: enhancement
