### ISSUE TITLE
Automatic pagination

### ISSUE THREAD

**Issue by pranabenator** [AmruthPillai/Reactive-Resume#1297] opened 2023-04-27 12:17 UTC
Don't find a way to automatic reflow of contents to a new page. It would be very useful. Else, please highlight section on howto.

**Comment by ssobhi1** [comment] 2023-05-25 16:51
Yes, I agree. Whenever I try to print my resume all of the content "fits" to 1 page. I understand this to be the case whenever the resume is downloaded as .pdf. Yet it would be beneficial to have the content appear on multiple pages and include an appropriate header.

**Comment by atsaloli** [comment] 2024-06-11 11:01
@AmruthPillai This is a duplicate of https://github.com/AmruthPillai/Reactive-Resume/issues/1834 (which has more discussion). Could we please close it to increase visiblity into open issues?

**Closed** 2024-06-12 05:38 UTC
Labels: enhancement
