### ISSUE TITLE
Difficulties in importing previously made resume with PDF and JSON files 

### ISSUE THREAD

**Issue by LavenderServer** [AmruthPillai/Reactive-Resume#320] opened 2020-09-01 22:57 UTC
Hello,
After importing a resume previously made from the website (doesn't matter if it's PDF or JSON), it either doesn't respond or leaves a blank page until I refresh it. Even after I refresh it, I still don't see the resume. Maybe it requires more loading time, but I'm not sure since there isn't a loading bar and it seems to work with the demo data after I refresh the page.

**Comment by ChristianVaughn** [comment] 2020-09-16 15:53
I am having the same exact issue. Below are 2 screenshots that might help solve the issue. I was attemping to import a ReactiveResume json file that I had exported back from the v1.x of the site. I don't know if the format of the resumes changed, or what is causing these react errors.
![image](https://user-images.githubusercontent.com/4643028/93361305-9364de00-f7f9-11ea-9983-f6908843a534.png)
![image](https://user-images.githubusercontent.com/4643028/93361426-b8595100-f7f9-11ea-85d8-715819aa3899.png)

**Comment by wal-Ega** [comment] 2020-10-13 13:31
Same issue happened with me while trying to import a previously exported JSON resume.

**Comment by ChristianVaughn** [comment] 2020-10-13 14:10
@wal-Ega Is your JSON resume from v1 of the reactive resume or v2? I found out recently that my issue is caused by trying to load a Reactive Resume v1 JSON file in Reactive Resume v2. Amruth mentioned this in issue #327.

**Comment by wal-Ega** [comment] 2020-10-13 16:47
@ChristianVaughn My JSON file is from v2 and when I try to import it back it straight after exporting it (from Reactive Resume v2.2.1), it result in a blank page, just like the one you included in a your original comment.

**Comment by AmruthPillai** [comment] 2022-03-08 14:08
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!

**Closed by AmruthPillai** 2022-03-08 14:08 UTC
Labels: bug
