### ISSUE TITLE
Exporting cvs to pdf makes the text centered

### ISSUE THREAD

**Issue by skerrepy** [AmruthPillai/Reactive-Resume#393] opened 2020-12-07 21:36 UTC
[my cv.pdf](https://github.com/AmruthPillai/Reactive-Resume/files/5655375/my.cv.pdf)

but in the link it looks fine:
https://rxresu.me/r/dg93lj
weird behavior

**Comment by MarionMoseby** [comment] 2020-12-08 00:28
Duplicate of #387

**Closed** 2020-12-08 09:14 UTC
