### ISSUE TITLE
currently one header suppose skills in the reactive resume is not being able to split into two parts so that it appears exactly on a A4 size paper , rather it extends the page size to cover all points in the skills section. Will be really thankful if you can add this feature in this sesction

### ISSUE THREAD

**Issue by sagarrastogi29** [AmruthPillai/Reactive-Resume#1086] opened 2022-11-18 04:51 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by atsaloli** [comment] 2024-06-11 11:02
@AmruthPillai This is a duplicate of https://github.com/AmruthPillai/Reactive-Resume/issues/1834  Could we please close it to increase visiblity into open issues?

**Closed** 2024-06-12 05:38 UTC
Labels: enhancement
