### ISSUE TITLE
[Bug] French dates translation fallback to English when exporting to PDF

### ISSUE THREAD

**Issue by sehnryr** [AmruthPillai/Reactive-Resume#1477] opened 2023-09-18 22:06 UTC
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

When exporting to PDF, dates are translated back to the English format. Using the MMM YYYY date format, "sept. 2020" is exported as "Sep 2020".

### Expected Behavior

French dates should be exported correctly.

### Steps To Reproduce

1. Create a resume
2. Add a field with shown dates, like the birth date or certification date.
3. Translate resume to French in the settings (if not already) and see the dates correctly displayed on the web interface
4. Export to PDF
5. Cry since dates are shown in English (sept. 2020 -> Sep 2020)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Anything else?

There was already this issue open #1213 but its title was not really explanatory and they were on MacOS using Firefox and Safari.

I did not try using https://github.com/AmruthPillai/Reactive-Resume/tree/v3.6.6 but I guess it worked then as this comment suggested https://github.com/AmruthPillai/Reactive-Resume/issues/1003#issuecomment-1248429657.

**Comment by AmruthPillai** [comment] 2023-09-19 06:52
Duplicate of https://github.com/AmruthPillai/Reactive-Resume/issues/1202

**Closed by AmruthPillai** 2023-09-19 06:52 UTC
