### ISSUE TITLE
[BUG] Alignment issues on Glalie (V3)

### ISSUE THREAD

**Issue by Markg546** [AmruthPillai/Reactive-Resume#753] opened 2022-03-21 08:07 UTC
**Describe the bug**

The date and email doesn't fit in the default Glalie template. I have fixed the email problem by using css. Also modified the name to be in 2 lines (just like in V2). But I was not able to make the date fit as I don't know how to acces it though css.

**Product Flavor**
- [X] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Go to website
2. Click on the Glalie template
3. For example write a longer award
4. The date doesn't fit

**Expected behavior**

I expect stuff to behave like in V2 (that being languages centered and dates fitting), or at least have an option to make it behave like that through css.

**Screenshots**

![Screenshot_20220321-094940_InstaPro](https://user-images.githubusercontent.com/11317615/159223649-cbea769b-c080-45d0-b59f-4cc61f36f40a.jpg)

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by chandiwalaaadhar** [comment] 2022-03-28 14:38
@AmruthPillai Can you please close this, as this is a duplicate of #758

**Closed** 2022-03-28 14:39 UTC
Labels: bug
