### ISSUE TITLE
Resume does not export to pdf

### ISSUE THREAD

**Issue by francivdberg** [AmruthPillai/Reactive-Resume#671] opened 2022-03-13 09:45 UTC
Hi Amruth!

Thank you for a great app. It has been really helpful, especially as a recent graduate. 

I recently experienced that every time I want to export my resume it saves and when I open the pdf it is looks like this (see screenshot).

![image](https://user-images.githubusercontent.com/101501207/158053871-0317c321-d9a7-4229-8eeb-bf725da1acd4.png)
 
Can you help me? I am already logged in.

**Comment by kameshkotwani** [comment] 2022-03-13 10:39
I am also facing the same issue.

**Comment by agucova** [comment] 2022-03-14 04:44
Duplicate of #670, I can also replicate the problem. Seems to be because of the v3 launch

**Comment by francivdberg** [comment] 2022-03-14 04:58
Does anyone know how to fix it?

**Comment by AmruthPillai** [comment] 2022-03-14 05:17
The print functionality in https://v2.rxresu.me should be fixed now, deployed a new version of the cloud function to print.

**Closed by AmruthPillai** 2022-03-14 05:17 UTC
Labels: bug, v2

**Comment by AmruthPillai** [comment] 2022-03-14 20:53
You can now import JSON files exported through https://v2.rxresu.me, as of [v3.2.3](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.2.3) 🎉
