### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by nicosea** [AmruthPillai/Reactive-Resume#430] opened 2021-01-24 13:24 UTC
When I try to access the start page, I see the welcome page for less than a second and than only a full black screen in the browser.

I am using docker image on Synology NAS.

**Comment by AmruthPillai** [comment] 2021-01-24 15:39
While using docker image, you also need to add .env to your volume with filled in values.

https://github.com/AmruthPillai/Reactive-Resume/blob/develop/.env.example

https://github.com/AmruthPillai/Reactive-Resume#building-from-source

**Comment by wiebereu** [comment] 2021-01-25 12:00
What are the values i have to fill in? Im not that experience linux user. Where can i find the information?

**Comment by AmruthPillai** [comment] 2021-01-25 12:45
It's not related to Linux, but actually Firebase. You can create a new Firebase project by following this guide: https://www.youtube.com/watch?v=6juww5Lmvgo

Then you would get all the values as part of a JSON. You would need to fill these values into `.env` as explained in the "Building from Source" section of the README.md.

**Comment by wiebereu** [comment] 2021-01-25 14:10
But it don't answer my question why the docker container first worked flawlessly and suddenly it stopped working?

**Comment by AmruthPillai** [comment] 2021-01-25 14:46
Oh, now that makes sense :) You were on the old version. The new version now has a lot more features, which requires an actual database.

If you would like to use the older version, you can visit https://v1.rxresu.me or if you would like to run it from docker, there's a v1 tag for the release: https://hub.docker.com/layers/amruthpillai/reactive-resume/v1/images/sha256-8078fcbf892c5c551df87b3ad4b8cde55afd7998887081ee0b5b301ff3ff7b35?context=repo

**Comment by wiebereu** [comment] 2021-01-25 19:52
I could not find information about the database url in the firebase project. The other information i found when i register the project, but not about the database url

**Comment by nicosea** [comment] 2021-01-27 20:11
Same problem, well actually I think I found the database url, but not the MEASUREMENTID. 
Anyway where to save the .env file in docker?

**Comment by AmruthPillai** [comment] 2021-01-28 05:06
You can follow these steps to load envs onto your docker container: https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files

**Comment by wiebereu** [comment] 2021-01-31 19:31
You are closing the issue but you haven't asked if is was resolved. I added the env file to my docker compose file and it didn't solve the problem. Than is added the variables in the env file directly to the docker compose file, cause the env is only necessary if you are in a open source situation which you share your docker compose file with other people. That is not the situation in my case so why not adding the variable to my dockerfile i thought. In both situation the black screen problem persist. 

You also said if i follow the steps with Firebase i will get all the information i needed. I did get most of the information but the information about the database url which is one of the variables in the env file i couldn't find. 
I don't understand why a user of this image: [https://registry.hub.docker.com/r/amruthpillai/reactive-resume/]  have to do a lot of manual configuration before the image works. If it is a beta version i would understand it

**Comment by kobemtl** [comment] 2021-05-13 12:00
Hi, I can reproduce the same problem. Here is what I did. 

1. Created project on Firebase, with all parameters need from the config.
2. Using the [template](https://github.com/AmruthPillai/Reactive-Resume/blob/develop/.env.example) create local env file, fill in all parameters from Firebase
3. Run the docker command `docker run --env-file ./env -d -p 80:80 amruthpillai/reactive-resume:latest` with env file
4. shell into the container check all env parameters have been load correctly. 

```shell
/ # env
FIREBASE_MEASUREMENTID="XXXXXXXXXXXXXXX"
FIREBASE_STORAGEBUCKET="XXXXXXXXXXXXXXX.appspot.com"
FIREBASE_AUTHDOMAIN="XXXXXXXXXXXXXXX.firebaseapp.com"
HOSTNAME=d91ecc9fc6e3
SHLVL=1
HOME=/root
PKG_RELEASE=1
FIREBASE_MESSAGINGSENDERID="XXXXXXXXXXXXXXX"
FIREBASE_PROJECTID="XXXXXXXXXXXXXXX"
FIREBASE_APPID="XXXXXXXXXXXXXXX"
TERM=xterm
NGINX_VERSION=1.19.10
FIREBASE_APIKEY="XXXXXXXXXXXXXXX"
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NJS_VERSION=0.5.3
FIREBASE_DATABASEURL="https://XXXXXXXXXXXXXXX.firebaseio.com/"
PWD=/
```
5. From Chrome use url http://localhost to access. I can see the app has been loaded then show black/blank page.
6. From Chrome Developer tool I can see the error 
```
react-dom.production.min.js:216 
N {code: "auth/invalid-api-key", message: "Your API key is invalid, please check you have copied it correctly.", a: null}
a: null
code: "auth/invalid-api-key"
message: "Your API key is invalid, please check you have copied it correctly."
```

I double checked several times my API key from Firebase is correct. Please help.

PS: 

If I use http://127.0.0.1 to access local container or run the container on remote host then using remote host ip to access the site, I get error `Service workers can only be used over HTTPS, or on localhost for development` with the same invalid api key error. I tried to setup reverse proxy to access the site, something like https://test.com/resume/, since there is no option for root url setting, the app redirect to https://test.com/ which is not good.

**Comment by RikardGehlin** [comment] 2021-06-26 23:30
I have the same behavior. API-key is correct but devtools claim it is wrong

**Comment by JiangLongLiu** [comment] 2021-09-18 10:18
I encountered the same problem. After adding the .env environment variable, I still got an error  

`Your API key is invalid, please check you have copied it correctly.`
![ab](https://user-images.githubusercontent.com/7019907/133885475-857cff16-b5be-42de-88ae-dc80095d6fc3.png)

**Comment by vnl** [comment] 2021-10-19 20:54
Following everything, I too am getting similar issues.

```
192.168.1.135/:1 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
register-service-worker.js:7 
        
       Service workers can only be used over HTTPS, or on localhost for development
70154 @ register-service-worker.js:7
react-dom.production.min.js:216 
        
       N
uu @ react-dom.production.min.js:216
react-dom.production.min.js:216 
        
       N
uu @ react-dom.production.min.js:216
scheduler.production.min.js:12 
        
       Uncaught Na: nullcode: "auth/invalid-api-key"message: "Your API key is invalid, please check you have copied it correctly."[[Prototype]]: Errorconstructor: ƒ N(t,e,n)toJSON: ƒ i()w: ƒ ()[[Prototype]]: Object
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Comment by AmruthPillai** [comment] 2022-03-08 14:02
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!

**Closed by AmruthPillai** 2022-03-08 14:02 UTC
