### ISSUE TITLE
Website URL Issue

### ISSUE THREAD

**Issue by TharVid** [AmruthPillai/Reactive-Resume#337] opened 2020-09-29 09:46 UTC
If you don't put HTTP or https website URL will look like0- https://rxresu.me/app/builder/www.example.org. Will work fine with HTTP or https. But having https and HTTP in a clickable link doesn't look cool.

**Comment by AmruthPillai** [comment] 2020-10-03 04:28
Duplicate of #307

**Closed by AmruthPillai** 2020-10-03 04:28 UTC
Labels: bug, good first issue
