### ISSUE TITLE
Downloading Resume in PDF (multiple pages)

### ISSUE THREAD

**Issue by junibond** [AmruthPillai/Reactive-Resume#1221] opened 2023-02-09 06:35 UTC
**Is your feature request related to a problem? Please describe.**

I have made my resume through the website and it's downloading as PDF but showing as one vertically long file instead of page size multiple pages in the PDF.

**Describe the solution you'd like**

PDF file to have multiple A4 pages

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by slim71** [comment] 2023-02-17 21:28
I've seen this too. Unfortunately it causes some other problems when trying to print the file, since the automatic choice of printers (at copy shops, at least) seems to be to scale down the PDF "image" to fit an A4 paper.
Is there more info I can give that can help?

**Comment by Benjamin-Medina** [comment] 2023-02-23 16:26
How I've worked around this problem is by adding a second page through the "layout" section of the left side panel. Unfortunately, I'm having issues with my first page appearing after exporting to pdf, despite presenting fine for the link.

**Comment by VigneshRamanathan101** [comment] 2024-04-05 18:28
@Benjamin-Medina I was able to get both pages intact and also their information

**Comment by atsaloli** [comment] 2024-06-11 11:01
@AmruthPillai This is a duplicate of https://github.com/AmruthPillai/Reactive-Resume/issues/1834  Could we please close it to increase visiblity into open issues?

**Closed** 2024-06-12 05:38 UTC
Labels: enhancement
