### ISSUE TITLE
Keywords tag should not be displayed with no keywords present

### ISSUE THREAD

**Issue by jelemux** [AmruthPillai/Reactive-Resume#659] opened 2022-03-12 11:44 UTC
What happens: If there are no keywords, the Keywords tag still gets shown in the resume.

Expected behaviour: If there are no keywords, the Keywords tag should not be shown.

**Comment by AmruthPillai** [comment] 2022-03-12 11:49
Duplicate of https://github.com/AmruthPillai/Reactive-Resume/issues/650, has been resolved now :)

**Closed by AmruthPillai** 2022-03-12 11:49 UTC
Labels: bug
