### ISSUE TITLE
Remove firebase dependency

### ISSUE THREAD

**Issue by HritwikSinghal** [AmruthPillai/Reactive-Resume#586] opened 2021-11-15 01:03 UTC
Hey, this project is awesome and kudos to you!
Can we remove the firebase NoSQL database dependency and use local database to store the info, or even store the Data in memory if we run it locally. 
The reason i am asking for this is that many people dont use google and thus dont have google account due to privacy reasons. And your app is one of the best apps for making resume while also being completely private and open source. So we cannot actually use this app without creating a google account. (i am not familiar with JS much and dont know if this can be bypassed temporarily)

i can try to work on it but i have no prior JS experience so would need help.

**Comment by HritwikSinghal** [comment] 2021-11-17 00:05
@gianantoniopini i see that you have privacy focus, can you help in this?

**Comment by AmruthPillai** [comment] 2021-11-17 07:53
The issue is not about removing Firebase as a database, but this app also uses Firebase heavily for authentication. While the database is easy to be switched out to a new one, I am yet to find a reasonable alternative for auth which can handle many users while being economically priced for open source projects.

I've also considered building an auth backend, but for a project at this scale, self made auth can go wrong in many places. I have to look for hosted alternatives, and nothing comes as easy as Firebase unfortunately.

**Comment by HritwikSinghal** [comment] 2021-11-17 15:21
> The issue is not about removing Firebase as a database, but this app also uses Firebase heavily for authentication. While the database is easy to be switched out to a new one, I am yet to find a reasonable alternative for auth which can handle many users while being economically priced for open source projects.

You can try other alternatives like
-  [superbase](https://supabase.io/) , 
- [back4app](https://www.back4app.com/). These both are open source too!. 
- [Here](https://medium.com/@brenda.clark/firebase-alternative-3-open-source-ways-to-follow-e45d9347bc8c) is another medium article.

> I've also considered building an auth backend, but for a project at this scale, self made auth can go wrong in many places. I have to look for hosted alternatives, and nothing comes as easy as Firebase unfortunately.

The problem that i am pointing out is when a user wants to self host or want to contribute to this project without creating firebase account. 

Suppose i want to build some feature or want to self host for my resume and i don't want google account. What i will do is i will not login with google (obviously) and not add my firebase creds, but want a temporary account which can be used to test the changes.

Lets look at some cases which i am referring to:
- CASE 1: I dont want to mess with anything: so i will use https://rxresu.me/ . In this case i can trust you to not store info (and since firebase is used with your API key, google cant track me.)
- I want to self host to create my resume: 
    - CASE 2.1: so if i will login with google to save my info, then i can also get firebase creds. In this case also no problem (But why self host then? i will probably use your hosted one)
    - CASE 2.2: If i dont want to login to google, i can use anonymous login but that requires firebase API which i will use if i don't care about my privacy with google. (But again why self host then? i will probably use your hosted one.)
    -CASE 2.3: However if i dont want any google tracking and want to self host, in this case i will not even use anonymous login and will not save my resume on even my server. What i will do is create my resume and export it in PDF as well as JSON so that next time i can directly import, modify, export, repeat.

Case 2.3 is the one i am referring to. This will also be helpful to test new changes since we no longer need any firebase API creds to create.

**Comment by HritwikSinghal** [comment] 2021-11-17 15:35
i Updated my previous comment so kindly read it on github (and not the one you got in mail)

**Comment by ParaplegicRacehorse** [comment] 2021-11-23 22:51
Okay.  So.  Auth is great for a hosted service, and you should absolutely use it especially if you're storing user data.

In my ideal use-case, I would fire up Reactive Resume in a Podman pod.  It's default save file type would plain text (think something along the lines of [JSON Resume](https://jsonresume.org/).)  It would further permit me to easily create PDF, ODT, and DOCX file types.

I =absolutely will not= store my data with Google.  Period.

I =would happily= pay you a reasonable fee to maintain a podman pod (or other OCI container.)

Consider an open core approach.  

- Open source core
-- OCI container with saves in plain text (JSON Resume, for example.)  

- Paid feature 
-- OCI container with saves in plain text && export to other popular formats (ODT, DOCX, PDF) with selection of attractive themes.

- Free service
-- This for those who don't care about sharing their data with you or with Google.
-- Able to export CV to plain text format.

- Paid service
-- In addition to free service, can export to popular formats and themes.

**Comment by AmruthPillai** [comment] 2021-11-23 23:19
I've been researching and working on POCs with Supabase quite a lot lately, and seems like a really good alternative that can be self-hosted and containerized into one bundle. This is an ongoing effort along with my vision to rebuild Reactive Resume under the NextJS web framework.

While I can't promise deadlines, it's definitely coming some day. I've learnt my lessons with Google and I can promise that you won't have to put up with them for too long, but to get motivated to rebuild Reactive Resume has been a huge hurdle for me with work and personal life. Nevertheless, Reactive Resume will always be one of my many priorities.

**Comment by HritwikSinghal** [comment] 2021-11-24 00:30
> While I can't promise deadlines, it's definitely coming some day. I've learnt my lessons with Google and I can promise that you won't have to put up with them for too long, but to get motivated to rebuild Reactive Resume has been a huge hurdle for me with work and personal life. Nevertheless, Reactive Resume will always be one of my many priorities.

Hey, don't worry, we are not expecting any deadlines from you :) . I know that you are working in your free time and are not getting paid for it (i too have some small open-source projects which i work on so i can understand your situation).

**Comment by ParaplegicRacehorse** [comment] 2021-11-24 15:06
Deadlines unimportant.  I don't expect to be unemployed again for another three months (gig worker) and then I think I won't be looking for work for a few months after.

And LibreOffice still functions very well.

**Comment by AmruthPillai** [comment] 2022-03-08 13:30
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!

**Closed by AmruthPillai** 2022-03-08 13:30 UTC

**Comment by HritwikSinghal** [comment] 2022-03-09 01:56
hi, i think we still need google keys in V3 as i can see 
```
# Auth
JWT_SECRET=change-me
JWT_EXPIRY_TIME=604800

# Google
PUBLIC_GOOGLE_CLIENT_ID=change-me
GOOGLE_CLIENT_SECRET=change-me
GOOGLE_API_KEY=change-me
```

in the env file. If so, can you please reopen this issue. Thanks

**Comment by AmruthPillai** [comment] 2022-03-09 10:16
It's not a necessary dependency, as it's not really required. You can read more in my comment here: https://github.com/AmruthPillai/Reactive-Resume/issues/636#issuecomment-1062689143 

The Google API Key right now is required because it is used to get a list of Google Fonts, but I'll work on a fallback in future versions.
