### ISSUE TITLE
Error while running own instance of the app

### ISSUE THREAD

**Issue by Mohan-cloud** [AmruthPillai/Reactive-Resume#298] opened 2020-08-10 07:49 UTC
I was able to login using the anonymous option. But when I visit the http://localhost:8000/app/dashboard link, I get the following error.

>  Router: Children of  Router must have a `path` or `default` prop, or be a `<Redirect>`. None found on element type 
  `function Redirect(props) {
  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(
    BaseContext.Consumer,
    null,
    function (_ref7) {
      var baseuri = _ref7.baseuri;
      return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(
        Location,
        null,
        function (locationContext) {
          return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(RedirectImpl, _extends({}, locationContext, { baseuri: baseuri }, props));
        }
      );
    }
  );
}`

**Comment by robert-w-gries** [comment] 2020-08-10 21:28
Found a workaround from [this thread](https://github.com/reach/router/issues/153). Doesn't seem like an ideal solution though

```diff
diff --git a/src/pages/app.js b/src/pages/app.js
index e77557f..6d46e70 100644
--- a/src/pages/app.js
+++ b/src/pages/app.js
@@ -9,7 +9,7 @@ import Dashboard from './app/dashboard';
 const App = () => (
   <Wrapper>
     <Router>
-      <Redirect noThrow from="/app" to="/app/dashboard" exact />
+      <Redirect noThrow path="/app" to="/app/dashboard" exact />
       <PrivateRoute path="/app/dashboard" component={Dashboard} />
       <PrivateRoute path="/app/builder/:id" component={Builder} />
       <NotFound default />
diff --git a/src/pages/r.js b/src/pages/r.js
index 5392c59..9cc01d8 100644
--- a/src/pages/r.js
+++ b/src/pages/r.js
@@ -7,7 +7,7 @@ import NotFound from './404';
 const ResumeRouter = () => (
   <Wrapper>
     <Router>
-      <Redirect noThrow from="/r" to="/" exact />
+      <Redirect noThrow path="/r" to="/" exact />
       <ResumeViewer path="r/:id" />
       <NotFound default />
     </Router>
```

**Comment by Mohan-cloud** [comment] 2020-08-11 04:26
Thanks mate, its working now.

**Comment by robert-w-gries** [comment] 2020-08-11 15:44
I don't think the issue should be closed since there isn't a solution yet. The workaround above just bypasses the problem of webpack and the hot loader not working well together.

Here is the relevant Gatsby issue: https://github.com/gatsbyjs/gatsby/issues/11934

The problem is only seen while running the development server. If you use `npm run build && npm run serve`, the issue isn't seen.

There are two solutions listed in the link above:

1) Use `@hot-loader/react-dom`

2) Use `fast-refresh` as the hot loader as `react-hot-loader` is [being deprecated](https://github.com/gaearon/react-hot-loader#moving-towards-next-step). Adding `GATSBY_HOT_LOADER=fast-refresh` to the `.env` file is confirmed to work with `npm run start`

I think solution 2 is the way to go since `react-hot-loader` is being deprecated.

**Comment by Mohan-cloud** [comment] 2020-08-12 09:42
I prematurely closed the issue, my mistake. I'm new to git and react.

**Comment by robert-w-gries** [comment] 2020-08-13 15:57
No worries! The author, @AmruthPillai, can re-open the issue if he wishes.

Thanks for filing the issue in the first place, it helped me realize I wasn't the only one seeing the problem.

**Comment by AmruthPillai** [comment] 2020-08-13 17:45
Will look into this :) Thank you for bringing it to my attention @robert-w-gries and @Mohan-cloud!

**Comment by insuusvenerati** [comment] 2020-08-25 16:48
Setting the `default` prop in `<Redirect noThrow from="/app" to="/app/dashboard" exact default />` fixed the issue for me

**Comment by HristovCodes** [comment] 2020-11-28 15:30
> Setting the `default` prop in `<Redirect noThrow from="/app" to="/app/dashboard" exact default />` fixed the issue for me

This also fixed it for me.

**Comment by AmruthPillai** [comment] 2022-03-08 14:08
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!

**Closed by AmruthPillai** 2022-03-08 14:08 UTC
