### ISSUE TITLE
hello I cannot download or export PDF my resume[BUG] 

### ISSUE THREAD

**Issue by AmirShah007** [AmruthPillai/Reactive-Resume#1099] opened 2022-11-24 06:58 UTC
**Describe the bug**

**Product Flavor**

- [ ] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Browser 
- Version 

**Additional context**

**Comment by tryallthethings** [comment] 2022-11-24 14:16
Hello! Your issue provided no information at all about your problem. Please provide some details and someone might be able to help you.

**Comment by rohanrdy** [comment] 2022-11-24 15:45
Hey even I am unable to export the pdf.
Can you please help me out by exporting this [^1] as a pdf? I have to submit my resume very soon and I will be really grateful for that. @tryallthethings @AmruthPillai (Sorry for the tags its urgent...)

Thanking you

[^1]: https://drive.google.com/file/d/1-3DOMNdiWnzbA5r4Fj3zX1JnuUMdnfU_/view?usp=share_link

**Comment by jgeorge97** [comment] 2022-11-24 17:36
I, too, have faced this same issue, here is the error in the console

<img width="1432" alt="Screenshot 2022-11-24 at 10 18 18 PM" src="https://user-images.githubusercontent.com/26036060/203841299-142d527c-c057-4689-b2a1-c21cddf61cd4.png">

**Comment by johnnypark777** [comment] 2022-11-24 20:21
> I, too, have faced this same issue, here is the error in the console
> 
> <img alt="Screenshot 2022-11-24 at 10 18 18 PM" width="1432" src="https://user-images.githubusercontent.com/26036060/203841299-142d527c-c057-4689-b2a1-c21cddf61cd4.png">

I get the exact error as the comment above. I suspect anybody who would like to have pdf exported and is using the web hosted [https://rxresu.me/](url) can reproduce this issue. Additionally, it looks like there is some sort of a timeout error, it attempts to get the pdf for approximately 37 seconds then would return this error.

![image](https://user-images.githubusercontent.com/45082451/203858520-513eeb9d-f685-4456-919d-cee5e541d58c.png)

**Comment by AmruthPillai** [comment] 2022-11-24 21:36
The issue should be fixed now, sorry for the delay and inconvenience.

**Closed by AmruthPillai** 2022-11-24 21:36 UTC
Labels: bug
