### ISSUE TITLE
[FEATURE] Card slide for the screenshots

### ISSUE THREAD

**Issue by arunkarthicknm** [AmruthPillai/Reactive-Resume#1019] opened 2022-10-03 10:10 UTC
Can use cards and make a quick slide for the screenshots as now it takes to new tab.
If it's reasonable I can work on this :)

**Comment by AmruthPillai** [comment] 2022-10-03 11:16
Looks like a duplicate of https://github.com/AmruthPillai/Reactive-Resume/issues/1014, correct me if I'm wrong :)

**Closed by AmruthPillai** 2022-10-03 11:16 UTC
Labels: enhancement
